description: "Mouse salivary gland (SMG) epithelial tissue"
dataset: "gland"
data_folder_name: "gland"

simulation:
  dimension: 3
  n_cells: 8000
  n_cell_types: 1
  n_frames: 553
  delta_t: 5.0
  max_radius: 0.02
  min_radius: 0
  sigma: 0.005
  boundary: "no"
  dpos_init: 0
  cell_params: [[1.0, 1.0, 1.0, 1.0]]
  func_params: [["arbitrary", 0, 0]]

graph_model:
  cell_model_name: "arbitrary_ode"
  mesh_model_name: ""
  prediction: "first_derivative"
  input_size: 6
  output_size: 3
  hidden_dim: 128
  n_layers: 5
  aggr_type: "mean"
  embedding_dim: 2
  update_type: "none"

plotting:
  colormap: "tab10"
  arrow_length: 2
  ylim: [-0.04, 0.03]

training:
  n_runs: 1
  device: "auto"
  n_epochs: 20
  batch_size: 4
  small_init_batch_size: False
  sparsity: "replace_embedding_function"
  cluster_method: "distance_plot"
  rotation_augmentation: True
  data_augmentation_loop: 20
  fix_cluster_embedding: True
